#!/bin/bash

apt-get update && apt-get install -y build-essential \
    openssl \
    libssl-dev \
    libiodbc2 \
    libiodbc2-dev \
    libmysqlclient-dev \
    libboost-all-dev \
    libprotobuf-dev \
    libpoco-doc \
    libpoco-dev \
    protobuf-compiler \
    clang-3.6 \
    clang-format-3.6 \
    ninja-build \
    wget \
    git \
    python3 \
    python3-pip \
    && pip3 install conan \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

cd /usr/local/src \
    && wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz \
    && tar xvf cmake-3.15.2.tar.gz \
    && cd cmake-3.15.2 \
    && ./bootstrap \
    && make \
    && make install \
    && cd .. \
    && rm -rf cmake*

wget https://pocoproject.org/releases/poco-1.9.4/poco-1.9.4-all.tar.gz \
    && tar xvf poco-1.9.4-all.tar.gz \
    && cd poco-1.9.4-all \
    && mkdir cmake-build \
    && cd cmake-build \
    && cmake .. \
    && cmake --build . --target install \
    && cd ../.. \
    && rm -rf poco*